# deployment.yaml for cepheid-ui
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cepheid-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cepheid-ui
  template:
    metadata:
      labels:
        app: cepheid-ui
    spec:
      containers:
      - name: cepheid-ui
        image: shapley/cepheid-ui:latest
        ports:
        - containerPort: 8080