version: '3.8'
services:
  iam-ui:
    container_name: iam-ui
    extends:
      file: docker-compose.common.yml
      service: iam-ui
    ports:
      - "8080:80"
    # environment:
    networks:
      - backend

  iam-ui-dev:
    container_name: iam-ui-dev
    extends:
      file: docker-compose.common.yml
      service: iam-ui-dev
    ports:
      - "8081:80"
    volumes:
      - ./src:.
    # environment:
    networks:
      - backend

networks:
  backend: